import type { VisualAssetEntry } from './types';

/**
 * Version 1.2A — pure asset **metadata**, deliberately free of any
 * `require(...)` call so this file can be imported directly by
 * `scripts/validate-visual-assets.mjs` under plain Node (Node cannot
 * `require()` a `.webp`/`.png` file the way Metro can).
 *
 * `src/assets/manifest/visualAssetManifest.ts` is the RN-facing module —
 * it imports this file and attaches the real, statically-required
 * `source` for each non-code-driven id. Keep this file and that file's
 * `ASSET_SOURCES` map in sync by id; the validation script checks that
 * every non-code-driven metadata id resolves to a real static require.
 */
export type VisualAssetMetadata = Omit<VisualAssetEntry, 'source'>;

export const VISUAL_ASSET_METADATA: readonly VisualAssetMetadata[] = [
  // ---------------------------------------------------------------------
  // Code-driven classic visuals (no image file — gradients/Views today).
  // ---------------------------------------------------------------------
  {
    id: 'classic_card_face_asset',
    type: 'card_face_texture',
    isCodeDriven: true,
    width: null,
    height: null,
    scale: null,
    aspectRatio: null,
    estimatedMemoryBytes: 0,
    preloadPriority: 'critical',
    fallbackAssetId: null,
    supportsDarkBackground: true,
    supportsLightBackground: true,
    reducedMotionAlternativeAssetId: null,
    platformSupport: ['ios', 'android', 'web'],
    assetVersion: 1,
  },
  {
    id: 'classic_card_back_asset',
    type: 'card_back_texture',
    isCodeDriven: true,
    width: null,
    height: null,
    scale: null,
    aspectRatio: null,
    estimatedMemoryBytes: 0,
    preloadPriority: 'critical',
    fallbackAssetId: null,
    supportsDarkBackground: true,
    supportsLightBackground: true,
    reducedMotionAlternativeAssetId: null,
    platformSupport: ['ios', 'android', 'web'],
    assetVersion: 1,
  },
  {
    id: 'ember_card_back_asset',
    type: 'card_back_texture',
    isCodeDriven: true,
    width: null,
    height: null,
    scale: null,
    aspectRatio: null,
    estimatedMemoryBytes: 0,
    preloadPriority: 'normal',
    fallbackAssetId: 'classic_card_back_asset',
    supportsDarkBackground: true,
    supportsLightBackground: true,
    reducedMotionAlternativeAssetId: null,
    platformSupport: ['ios', 'android', 'web'],
    assetVersion: 1,
  },
  {
    id: 'midnight_card_face_asset',
    type: 'card_face_texture',
    isCodeDriven: true,
    width: null,
    height: null,
    scale: null,
    aspectRatio: null,
    estimatedMemoryBytes: 0,
    preloadPriority: 'normal',
    fallbackAssetId: 'classic_card_face_asset',
    supportsDarkBackground: true,
    supportsLightBackground: false,
    reducedMotionAlternativeAssetId: null,
    platformSupport: ['ios', 'android', 'web'],
    assetVersion: 1,
  },
  {
    id: 'classic_lane_overlay_asset',
    type: 'lane_overlay',
    isCodeDriven: true,
    width: null,
    height: null,
    scale: null,
    aspectRatio: null,
    estimatedMemoryBytes: 0,
    preloadPriority: 'critical',
    fallbackAssetId: null,
    supportsDarkBackground: true,
    supportsLightBackground: true,
    reducedMotionAlternativeAssetId: null,
    platformSupport: ['ios', 'android', 'web'],
    assetVersion: 1,
  },
  {
    id: 'gold_lane_overlay_asset',
    type: 'lane_overlay',
    isCodeDriven: true,
    width: null,
    height: null,
    scale: null,
    aspectRatio: null,
    estimatedMemoryBytes: 0,
    preloadPriority: 'normal',
    fallbackAssetId: 'classic_lane_overlay_asset',
    supportsDarkBackground: true,
    supportsLightBackground: true,
    reducedMotionAlternativeAssetId: null,
    platformSupport: ['ios', 'android', 'web'],
    assetVersion: 1,
  },
  {
    id: 'classic_profile_frame_asset',
    type: 'profile_frame',
    isCodeDriven: true,
    width: null,
    height: null,
    scale: null,
    aspectRatio: 1,
    estimatedMemoryBytes: 0,
    preloadPriority: 'critical',
    fallbackAssetId: null,
    supportsDarkBackground: true,
    supportsLightBackground: true,
    reducedMotionAlternativeAssetId: null,
    platformSupport: ['ios', 'android', 'web'],
    assetVersion: 1,
  },
  {
    id: 'flame_profile_frame_asset',
    type: 'profile_frame',
    isCodeDriven: true,
    width: null,
    height: null,
    scale: null,
    aspectRatio: 1,
    estimatedMemoryBytes: 0,
    preloadPriority: 'normal',
    fallbackAssetId: 'classic_profile_frame_asset',
    supportsDarkBackground: true,
    supportsLightBackground: true,
    reducedMotionAlternativeAssetId: null,
    platformSupport: ['ios', 'android', 'web'],
    assetVersion: 1,
  },
  {
    id: 'classic_board_overlay_asset',
    type: 'board_overlay',
    isCodeDriven: true,
    width: null,
    height: null,
    scale: null,
    aspectRatio: null,
    estimatedMemoryBytes: 0,
    preloadPriority: 'critical',
    fallbackAssetId: null,
    supportsDarkBackground: true,
    supportsLightBackground: true,
    reducedMotionAlternativeAssetId: null,
    platformSupport: ['ios', 'android', 'web'],
    assetVersion: 1,
  },
  {
    id: 'classic_victory_overlay_asset',
    type: 'victory_overlay',
    isCodeDriven: true,
    width: null,
    height: null,
    scale: null,
    aspectRatio: null,
    estimatedMemoryBytes: 0,
    preloadPriority: 'high',
    fallbackAssetId: null,
    supportsDarkBackground: true,
    supportsLightBackground: true,
    reducedMotionAlternativeAssetId: null,
    platformSupport: ['ios', 'android', 'web'],
    assetVersion: 1,
  },
  {
    id: 'ember_board_overlay_asset',
    type: 'board_overlay',
    isCodeDriven: true,
    width: null,
    height: null,
    scale: null,
    aspectRatio: null,
    estimatedMemoryBytes: 0,
    preloadPriority: 'low',
    fallbackAssetId: 'classic_board_overlay_asset',
    supportsDarkBackground: true,
    supportsLightBackground: false,
    reducedMotionAlternativeAssetId: null,
    platformSupport: ['ios', 'android', 'web'],
    assetVersion: 1,
  },
  {
    id: 'ember_victory_overlay_asset',
    type: 'victory_overlay',
    isCodeDriven: true,
    width: null,
    height: null,
    scale: null,
    aspectRatio: null,
    estimatedMemoryBytes: 0,
    preloadPriority: 'low',
    fallbackAssetId: 'classic_victory_overlay_asset',
    supportsDarkBackground: true,
    supportsLightBackground: false,
    reducedMotionAlternativeAssetId: null,
    platformSupport: ['ios', 'android', 'web'],
    assetVersion: 1,
  },
  {
    id: 'lava_arena_tint_asset',
    type: 'arena_background',
    isCodeDriven: true,
    width: null,
    height: null,
    scale: null,
    aspectRatio: null,
    estimatedMemoryBytes: 0,
    preloadPriority: 'normal',
    fallbackAssetId: 'classic_arena_gameplay_asset',
    supportsDarkBackground: true,
    supportsLightBackground: false,
    reducedMotionAlternativeAssetId: null,
    platformSupport: ['ios', 'android', 'web'],
    assetVersion: 1,
  },

  // ---------------------------------------------------------------------
  // Existing static textures (reused from src/assets/blazeAssets.ts —
  // real `require(...)` sources are attached in visualAssetManifest.ts).
  // ---------------------------------------------------------------------
  {
    id: 'classic_arena_home_asset',
    type: 'arena_background',
    isCodeDriven: false,
    width: 720,
    height: 1600,
    scale: 2,
    aspectRatio: 720 / 1600,
    estimatedMemoryBytes: 720 * 1600 * 4,
    preloadPriority: 'critical',
    fallbackAssetId: null,
    supportsDarkBackground: true,
    supportsLightBackground: false,
    reducedMotionAlternativeAssetId: null,
    platformSupport: ['ios', 'android', 'web'],
    assetVersion: 1,
  },
  {
    id: 'classic_arena_gameplay_asset',
    type: 'arena_background',
    isCodeDriven: false,
    width: 1080,
    height: 2400,
    scale: 3,
    aspectRatio: 1080 / 2400,
    estimatedMemoryBytes: 1080 * 2400 * 4,
    preloadPriority: 'critical',
    fallbackAssetId: null,
    supportsDarkBackground: true,
    supportsLightBackground: false,
    reducedMotionAlternativeAssetId: null,
    platformSupport: ['ios', 'android', 'web'],
    assetVersion: 1,
  },
  {
    id: 'classic_arena_gameplay_subtle_asset',
    type: 'arena_background',
    isCodeDriven: false,
    width: 1080,
    height: 2400,
    scale: 3,
    aspectRatio: 1080 / 2400,
    estimatedMemoryBytes: 1080 * 2400 * 4,
    preloadPriority: 'high',
    fallbackAssetId: 'classic_arena_gameplay_asset',
    supportsDarkBackground: true,
    supportsLightBackground: false,
    reducedMotionAlternativeAssetId: null,
    platformSupport: ['ios', 'android', 'web'],
    assetVersion: 1,
  },
  {
    id: 'ember_overlay_particle_asset',
    type: 'particle_sprite',
    isCodeDriven: false,
    width: 1024,
    height: 2048,
    scale: 2,
    aspectRatio: 1024 / 2048,
    estimatedMemoryBytes: 1024 * 2048 * 4,
    preloadPriority: 'low',
    fallbackAssetId: null,
    supportsDarkBackground: true,
    supportsLightBackground: false,
    reducedMotionAlternativeAssetId: null,
    platformSupport: ['ios', 'android', 'web'],
    assetVersion: 1,
  },
] as const;
