/**
 * Expo replaces EXPO_PUBLIC_* variables only when they are referenced with
 * static dot notation. Keep every client-visible environment read in this
 * switch so Metro can inline values into release bundles.
 *
 * Do not replace these cases with process.env[name], bracket notation, or
 * destructuring: those forms are not supported by Expo environment inlining.
 */
export type PublicEnvName =
  | 'EXPO_PUBLIC_SUPABASE_URL'
  | 'EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY'
  | 'EXPO_PUBLIC_APP_ENV'
  | 'EXPO_PUBLIC_BUILD_PROFILE'
  | 'EXPO_PUBLIC_ENABLE_PURCHASE_DIAGNOSTICS'
  | 'EXPO_PUBLIC_ENABLE_LIVE_DUEL'
  | 'EXPO_PUBLIC_ENABLE_QUICK_MATCH'
  | 'EXPO_PUBLIC_ENABLE_RANKED_BETA'
  | 'EXPO_PUBLIC_ENABLE_MONETIZATION_BETA'
  | 'EXPO_PUBLIC_ENABLE_REWARDED_ADS'
  | 'EXPO_PUBLIC_ENABLE_REWARDED_CURRENCY'
  | 'EXPO_PUBLIC_ENABLE_INTERSTITIAL_ADS'
  | 'EXPO_PUBLIC_ENABLE_STORE_PURCHASES'
  | 'EXPO_PUBLIC_ADMOB_USE_TEST_ADS'
  | 'EXPO_PUBLIC_ENABLE_PROGRESSION_BETA'
  | 'EXPO_PUBLIC_ENABLE_V1_1_REWARDS'
  | 'EXPO_PUBLIC_ENABLE_DAILY_REWARDS'
  | 'EXPO_PUBLIC_ENABLE_DAILY_MISSIONS'
  | 'EXPO_PUBLIC_ENABLE_V1_3_PROGRESSION'
  | 'EXPO_PUBLIC_ENABLE_V1_1_LOCKER'
  | 'EXPO_PUBLIC_ENABLE_V1_2_VISUAL_SYSTEM'
  | 'EXPO_PUBLIC_ENABLE_THEME_PREVIEW_DEV'
  | 'EXPO_PUBLIC_ENABLE_BOARD_EFFECTS'
  | 'EXPO_PUBLIC_ENABLE_VICTORY_EFFECTS'
  | 'EXPO_PUBLIC_ENABLE_DAILY_CHALLENGE'
  | 'EXPO_PUBLIC_ENABLE_DAILY_CHALLENGE_RANKED'
  | 'EXPO_PUBLIC_ENABLE_DAILY_CHALLENGE_PRACTICE'
  | 'EXPO_PUBLIC_ENABLE_DAILY_LEADERBOARD'
  | 'EXPO_PUBLIC_ENABLE_ASYNC_DUEL'
  | 'EXPO_PUBLIC_ENABLE_LIVE_PVP'
  | 'EXPO_PUBLIC_ADMOB_IOS_APP_ID'
  | 'EXPO_PUBLIC_ADMOB_ANDROID_APP_ID'
  | 'EXPO_PUBLIC_ADMOB_REWARDED_IOS_ID'
  | 'EXPO_PUBLIC_ADMOB_REWARDED_ANDROID_ID'
  | 'EXPO_PUBLIC_ADMOB_INTERSTITIAL_IOS_ID'
  | 'EXPO_PUBLIC_ADMOB_INTERSTITIAL_ANDROID_ID'
  | 'EXPO_PUBLIC_REVENUECAT_API_KEY'
  | 'EXPO_PUBLIC_REVENUECAT_IOS_API_KEY'
  | 'EXPO_PUBLIC_REVENUECAT_ANDROID_API_KEY';

export function readPublicEnv(name: PublicEnvName): string {
  let value: string | undefined;
  switch (name) {
    case 'EXPO_PUBLIC_SUPABASE_URL': value = process.env.EXPO_PUBLIC_SUPABASE_URL; break;
    case 'EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY': value = process.env.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY; break;
    case 'EXPO_PUBLIC_APP_ENV': value = process.env.EXPO_PUBLIC_APP_ENV; break;
    case 'EXPO_PUBLIC_BUILD_PROFILE': value = process.env.EXPO_PUBLIC_BUILD_PROFILE; break;
    case 'EXPO_PUBLIC_ENABLE_PURCHASE_DIAGNOSTICS': value = process.env.EXPO_PUBLIC_ENABLE_PURCHASE_DIAGNOSTICS; break;
    case 'EXPO_PUBLIC_ENABLE_LIVE_DUEL': value = process.env.EXPO_PUBLIC_ENABLE_LIVE_DUEL; break;
    case 'EXPO_PUBLIC_ENABLE_QUICK_MATCH': value = process.env.EXPO_PUBLIC_ENABLE_QUICK_MATCH; break;
    case 'EXPO_PUBLIC_ENABLE_RANKED_BETA': value = process.env.EXPO_PUBLIC_ENABLE_RANKED_BETA; break;
    case 'EXPO_PUBLIC_ENABLE_MONETIZATION_BETA': value = process.env.EXPO_PUBLIC_ENABLE_MONETIZATION_BETA; break;
    case 'EXPO_PUBLIC_ENABLE_REWARDED_ADS': value = process.env.EXPO_PUBLIC_ENABLE_REWARDED_ADS; break;
    case 'EXPO_PUBLIC_ENABLE_REWARDED_CURRENCY': value = process.env.EXPO_PUBLIC_ENABLE_REWARDED_CURRENCY; break;
    case 'EXPO_PUBLIC_ENABLE_INTERSTITIAL_ADS': value = process.env.EXPO_PUBLIC_ENABLE_INTERSTITIAL_ADS; break;
    case 'EXPO_PUBLIC_ENABLE_STORE_PURCHASES': value = process.env.EXPO_PUBLIC_ENABLE_STORE_PURCHASES; break;
    case 'EXPO_PUBLIC_ADMOB_USE_TEST_ADS': value = process.env.EXPO_PUBLIC_ADMOB_USE_TEST_ADS; break;
    case 'EXPO_PUBLIC_ENABLE_PROGRESSION_BETA': value = process.env.EXPO_PUBLIC_ENABLE_PROGRESSION_BETA; break;
    case 'EXPO_PUBLIC_ENABLE_V1_1_REWARDS': value = process.env.EXPO_PUBLIC_ENABLE_V1_1_REWARDS; break;
    case 'EXPO_PUBLIC_ENABLE_DAILY_REWARDS': value = process.env.EXPO_PUBLIC_ENABLE_DAILY_REWARDS; break;
    case 'EXPO_PUBLIC_ENABLE_DAILY_MISSIONS': value = process.env.EXPO_PUBLIC_ENABLE_DAILY_MISSIONS; break;
    case 'EXPO_PUBLIC_ENABLE_V1_3_PROGRESSION': value = process.env.EXPO_PUBLIC_ENABLE_V1_3_PROGRESSION; break;
    case 'EXPO_PUBLIC_ENABLE_V1_1_LOCKER': value = process.env.EXPO_PUBLIC_ENABLE_V1_1_LOCKER; break;
    case 'EXPO_PUBLIC_ENABLE_V1_2_VISUAL_SYSTEM': value = process.env.EXPO_PUBLIC_ENABLE_V1_2_VISUAL_SYSTEM; break;
    case 'EXPO_PUBLIC_ENABLE_THEME_PREVIEW_DEV': value = process.env.EXPO_PUBLIC_ENABLE_THEME_PREVIEW_DEV; break;
    case 'EXPO_PUBLIC_ENABLE_BOARD_EFFECTS': value = process.env.EXPO_PUBLIC_ENABLE_BOARD_EFFECTS; break;
    case 'EXPO_PUBLIC_ENABLE_VICTORY_EFFECTS': value = process.env.EXPO_PUBLIC_ENABLE_VICTORY_EFFECTS; break;
    case 'EXPO_PUBLIC_ENABLE_DAILY_CHALLENGE': value = process.env.EXPO_PUBLIC_ENABLE_DAILY_CHALLENGE; break;
    case 'EXPO_PUBLIC_ENABLE_DAILY_CHALLENGE_RANKED': value = process.env.EXPO_PUBLIC_ENABLE_DAILY_CHALLENGE_RANKED; break;
    case 'EXPO_PUBLIC_ENABLE_DAILY_CHALLENGE_PRACTICE': value = process.env.EXPO_PUBLIC_ENABLE_DAILY_CHALLENGE_PRACTICE; break;
    case 'EXPO_PUBLIC_ENABLE_DAILY_LEADERBOARD': value = process.env.EXPO_PUBLIC_ENABLE_DAILY_LEADERBOARD; break;
    case 'EXPO_PUBLIC_ENABLE_ASYNC_DUEL': value = process.env.EXPO_PUBLIC_ENABLE_ASYNC_DUEL; break;
    case 'EXPO_PUBLIC_ENABLE_LIVE_PVP': value = process.env.EXPO_PUBLIC_ENABLE_LIVE_PVP; break;
    case 'EXPO_PUBLIC_ADMOB_IOS_APP_ID': value = process.env.EXPO_PUBLIC_ADMOB_IOS_APP_ID; break;
    case 'EXPO_PUBLIC_ADMOB_ANDROID_APP_ID': value = process.env.EXPO_PUBLIC_ADMOB_ANDROID_APP_ID; break;
    case 'EXPO_PUBLIC_ADMOB_REWARDED_IOS_ID': value = process.env.EXPO_PUBLIC_ADMOB_REWARDED_IOS_ID; break;
    case 'EXPO_PUBLIC_ADMOB_REWARDED_ANDROID_ID': value = process.env.EXPO_PUBLIC_ADMOB_REWARDED_ANDROID_ID; break;
    case 'EXPO_PUBLIC_ADMOB_INTERSTITIAL_IOS_ID': value = process.env.EXPO_PUBLIC_ADMOB_INTERSTITIAL_IOS_ID; break;
    case 'EXPO_PUBLIC_ADMOB_INTERSTITIAL_ANDROID_ID': value = process.env.EXPO_PUBLIC_ADMOB_INTERSTITIAL_ANDROID_ID; break;
    case 'EXPO_PUBLIC_REVENUECAT_API_KEY': value = process.env.EXPO_PUBLIC_REVENUECAT_API_KEY; break;
    case 'EXPO_PUBLIC_REVENUECAT_IOS_API_KEY': value = process.env.EXPO_PUBLIC_REVENUECAT_IOS_API_KEY; break;
    case 'EXPO_PUBLIC_REVENUECAT_ANDROID_API_KEY': value = process.env.EXPO_PUBLIC_REVENUECAT_ANDROID_API_KEY; break;
  }
  return value?.trim() ?? '';
}
